version: "3.7"

services:
  api:
    build: .
    volumes:
      - ./:/application
    ports:
      - "8000:8000"
    depends_on:
      - database
    env_file: .env
    restart: always

  database:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ./initdb/dumps:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_db